# Generated by Django 4.1.2 on 2022-11-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='champion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('imgurl', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='game',
            fields=[
                ('gameid', models.AutoField(primary_key=True, serialize=False)),
                ('rnk', models.TextField()),
                ('kog', models.TextField()),
                ('vod', models.TextField()),
                ('gmt', models.TextField()),
                ('koc', models.TextField()),
                ('kda', models.TextField()),
                ('gpa', models.TextField()),
                ('prk', models.TextField()),
                ('ccw', models.TextField()),
                ('ccs', models.TextField()),
                ('prt', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='life_achievement',
            fields=[
                ('achievementid', models.AutoField(primary_key=True, serialize=False)),
                ('rnk', models.TextField()),
                ('kog', models.TextField()),
                ('vod', models.TextField()),
                ('gmt', models.TextField()),
                ('koc', models.TextField()),
                ('kda', models.TextField()),
                ('gpa', models.TextField()),
                ('prk', models.TextField()),
                ('ccw', models.TextField()),
                ('ccs', models.TextField()),
                ('prt', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='todaystotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('victory', models.IntegerField()),
                ('defeat', models.IntegerField()),
                ('draw', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
    ]
