# Generated by Django 4.1.2 on 2022-11-21 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lol_record', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='koc',
        ),
        migrations.RemoveField(
            model_name='life_achievement',
            name='koc',
        ),
        migrations.AddField(
            model_name='game',
            name='champion_id',
            field=models.ForeignKey(default='some_value', on_delete=django.db.models.deletion.CASCADE, to='lol_record.champion'),
        ),
        migrations.AddField(
            model_name='life_achievement',
            name='game_id',
            field=models.ForeignKey(default='some_value', on_delete=django.db.models.deletion.CASCADE, to='lol_record.game'),
        ),
    ]
