# Generated by Django 4.1.2 on 2022-11-21 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lol_record', '0002_remove_game_koc_remove_life_achievement_koc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='champion_id',
            field=models.ForeignKey(default='number', on_delete=django.db.models.deletion.CASCADE, to='lol_record.champion'),
        ),
        migrations.AlterField(
            model_name='life_achievement',
            name='game_id',
            field=models.ForeignKey(default='number', on_delete=django.db.models.deletion.CASCADE, to='lol_record.game'),
        ),
    ]
