# Generated by Django 4.1.2 on 2022-11-21 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lol_record', '0003_alter_game_champion_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='champion_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='lol_record.champion'),
        ),
        migrations.AlterField(
            model_name='life_achievement',
            name='game_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='lol_record.game'),
        ),
    ]
