# Generated by Django 4.1.2 on 2022-11-21 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lol_record', '0004_alter_game_champion_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='life_achievement',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lol_record.game'),
        ),
    ]
